/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SetStorageOptionDialog.java
 *
 * Created on May 20, 2009, 11:01:45 PM
 */
package graphicUserInterface;

import commandParser.ParserAndExecuterEngine.InfLevel;

import fuzzyRDFSEngine.*;

/**
 * 
 * @author feffo
 */
public class SetStorageOptionDialog extends javax.swing.JFrame implements
		Runnable {

	private final GUIView main;

	SetStorageOptionDialog(GUIView main) {
		this.main = main;
	}

	public void run() {
		initComponents();
		this.setVisible(true);
		this.setAlwaysOnTop(false);
		if (main.fuzzySystem != null) {
			msgLabel.setForeground(java.awt.Color.RED);
			msgLabel.setText("!!!!!!!!!! WARNING !!!!!!!!!!!!!!\n"
					+ "changing storage option now will result in"
					+ " loss of all graphs previously added\n"
					+ "!!!!!!!!!! WARNING !!!!!!!!!!!!!!\n");
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		buttonGroup2 = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		mainMemoryPanel = new javax.swing.JPanel();
		mainMemoryRB = new javax.swing.JRadioButton();
		monetPanel = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		monetRB = new javax.swing.JRadioButton();
		jPanel5 = new javax.swing.JPanel();
		localhostRB = new javax.swing.JRadioButton();
		otherLocationRB = new javax.swing.JRadioButton();
		locationField = new javax.swing.JTextField();
		jPanel6 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		databaseNameField = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		userNameField = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		passwordField = new javax.swing.JPasswordField();
		filePanel = new javax.swing.JPanel();
		fileRB = new javax.swing.JRadioButton();
		fileTextField = new javax.swing.JTextField();
		jPanel8 = new javax.swing.JPanel();
		doneButton = new javax.swing.JButton();
		jPanel9 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		msgLabel = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application
				.getInstance(graphicUserInterface.GUIMain.class).getContext()
				.getResourceMap(SetStorageOptionDialog.class);
		setTitle(resourceMap.getString("Form.title")); // NOI18N
		setName("Form"); // NOI18N

		jPanel1.setName("jPanel1"); // NOI18N

		jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
		jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
		jLabel1.setName("jLabel1"); // NOI18N

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addGap(345, 345, 345)
						.addComponent(jLabel1).addContainerGap(70,
								Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addComponent(jLabel1)
						.addContainerGap(13, Short.MAX_VALUE)));

		jSeparator1.setName("jSeparator1"); // NOI18N

		mainMemoryPanel.setBorder(javax.swing.BorderFactory
				.createTitledBorder(resourceMap
						.getString("mainMemoryPanel.border.title"))); // NOI18N
		mainMemoryPanel.setName("mainMemoryPanel"); // NOI18N

		buttonGroup1.add(mainMemoryRB);
		mainMemoryRB.setText(resourceMap.getString("mainMemoryRB.text")); // NOI18N
		mainMemoryRB.setName("mainMemoryRB"); // NOI18N
		mainMemoryRB.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				mainMemoryRBMouseClicked(evt);
			}
		});

		javax.swing.GroupLayout mainMemoryPanelLayout = new javax.swing.GroupLayout(
				mainMemoryPanel);
		mainMemoryPanel.setLayout(mainMemoryPanelLayout);
		mainMemoryPanelLayout.setHorizontalGroup(mainMemoryPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						mainMemoryPanelLayout.createSequentialGroup()
								.addContainerGap().addComponent(mainMemoryRB)
								.addContainerGap(501, Short.MAX_VALUE)));
		mainMemoryPanelLayout.setVerticalGroup(mainMemoryPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						mainMemoryPanelLayout.createSequentialGroup()
								.addComponent(mainMemoryRB).addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		monetPanel.setBorder(javax.swing.BorderFactory
				.createTitledBorder(resourceMap
						.getString("monetPanel.border.title"))); // NOI18N
		monetPanel.setName("monetPanel"); // NOI18N

		jPanel4.setName("jPanel4"); // NOI18N

		buttonGroup1.add(monetRB);
		monetRB.setSelected(true);
		monetRB.setText(resourceMap.getString("monetRB.text")); // NOI18N
		monetRB.setName("monetRB"); // NOI18N
		monetRB.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				monetRBMouseClicked(evt);
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel4Layout.createSequentialGroup().addContainerGap()
						.addComponent(monetRB).addContainerGap(485,
								Short.MAX_VALUE)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel4Layout.createSequentialGroup().addComponent(monetRB)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		jPanel5.setBorder(javax.swing.BorderFactory
				.createTitledBorder(resourceMap
						.getString("jPanel5.border.title"))); // NOI18N
		jPanel5.setName("jPanel5"); // NOI18N

		buttonGroup2.add(localhostRB);
		localhostRB.setSelected(true);
		localhostRB.setText(resourceMap.getString("localhostRB.text")); // NOI18N
		localhostRB.setName("localhostRB"); // NOI18N

		buttonGroup2.add(otherLocationRB);
		otherLocationRB.setText(resourceMap.getString("otherLocationRB.text")); // NOI18N
		otherLocationRB.setName("otherLocationRB"); // NOI18N

		locationField.setText(resourceMap.getString("locationField.text")); // NOI18N
		locationField.setName("locationField"); // NOI18N

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout
				.setHorizontalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel5Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(localhostRB)
										.addGap(30, 30, 30)
										.addComponent(otherLocationRB)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												locationField,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												455, Short.MAX_VALUE)
										.addContainerGap()));
		jPanel5Layout
				.setVerticalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel5Layout
										.createSequentialGroup()
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																localhostRB)
														.addComponent(
																otherLocationRB)
														.addComponent(
																locationField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jPanel6.setBorder(javax.swing.BorderFactory
				.createTitledBorder(resourceMap
						.getString("jPanel6.border.title"))); // NOI18N
		jPanel6.setName("jPanel6"); // NOI18N

		jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
		jLabel2.setName("jLabel2"); // NOI18N

		databaseNameField.setText(resourceMap
				.getString("databaseNameField.text")); // NOI18N
		databaseNameField.setName("databaseNameField"); // NOI18N

		jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
		jLabel3.setName("jLabel3"); // NOI18N

		userNameField.setText(resourceMap.getString("userNameField.text")); // NOI18N
		userNameField.setName("userNameField"); // NOI18N

		jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
		jLabel4.setName("jLabel4"); // NOI18N

		passwordField.setText(resourceMap.getString("passwordField.text")); // NOI18N
		passwordField.setName("passwordField"); // NOI18N

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout
				.setHorizontalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel2)
														.addComponent(jLabel3)
														.addComponent(jLabel4))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																passwordField)
														.addComponent(
																userNameField)
														.addComponent(
																databaseNameField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																141,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(442, Short.MAX_VALUE)));
		jPanel6Layout
				.setVerticalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																databaseNameField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2))
										.addGap(16, 16, 16)
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																userNameField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																passwordField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		javax.swing.GroupLayout monetPanelLayout = new javax.swing.GroupLayout(
				monetPanel);
		monetPanel.setLayout(monetPanelLayout);
		monetPanelLayout.setHorizontalGroup(monetPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		monetPanelLayout
				.setVerticalGroup(monetPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								monetPanelLayout
										.createSequentialGroup()
										.addComponent(
												jPanel4,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel5,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel6,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addContainerGap()));

		filePanel.setBorder(javax.swing.BorderFactory
				.createTitledBorder(resourceMap
						.getString("filePanel.border.title"))); // NOI18N
		filePanel.setName("filePanel"); // NOI18N

		buttonGroup1.add(fileRB);
		fileRB.setText(resourceMap.getString("fileRB.text")); // NOI18N
		fileRB.setName("fileRB"); // NOI18N
		fileRB.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				fileRBMouseClicked(evt);
			}
		});

		fileTextField.setText(resourceMap.getString("fileTextField.text")); // NOI18N
		fileTextField.setName("fileTextField"); // NOI18N

		javax.swing.GroupLayout filePanelLayout = new javax.swing.GroupLayout(
				filePanel);
		filePanel.setLayout(filePanelLayout);
		filePanelLayout.setHorizontalGroup(filePanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				filePanelLayout.createSequentialGroup().addContainerGap()
						.addComponent(fileRB).addGap(18, 18, 18).addComponent(
								fileTextField,
								javax.swing.GroupLayout.PREFERRED_SIZE, 304,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(251, Short.MAX_VALUE)));
		filePanelLayout
				.setVerticalGroup(filePanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								filePanelLayout
										.createSequentialGroup()
										.addGroup(
												filePanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(fileRB)
														.addComponent(
																fileTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jPanel8.setName("jPanel8"); // NOI18N

		doneButton.setText(resourceMap.getString("doneButton.text")); // NOI18N
		doneButton.setName("doneButton"); // NOI18N
		doneButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				doneButtonMouseClicked(evt);
			}
		});

		javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(
				jPanel8);
		jPanel8.setLayout(jPanel8Layout);
		jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel8Layout.createSequentialGroup().addGap(298, 298, 298)
						.addComponent(doneButton).addContainerGap(307,
								Short.MAX_VALUE)));
		jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel8Layout.createSequentialGroup().addContainerGap()
						.addComponent(doneButton).addContainerGap(24,
								Short.MAX_VALUE)));

		jPanel9.setName("jPanel9"); // NOI18N

		jScrollPane1.setName("jScrollPane1"); // NOI18N

		msgLabel.setColumns(20);
		msgLabel.setRows(5);
		msgLabel.setName("msgLabel"); // NOI18N
		jScrollPane1.setViewportView(msgLabel);

		javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(
				jPanel9);
		jPanel9.setLayout(jPanel9Layout);
		jPanel9Layout.setHorizontalGroup(jPanel9Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736,
				Short.MAX_VALUE));
		jPanel9Layout.setVerticalGroup(jPanel9Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 71,
				Short.MAX_VALUE));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jSeparator1,
						javax.swing.GroupLayout.DEFAULT_SIZE, 736,
						Short.MAX_VALUE).addComponent(mainMemoryPanel,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(monetPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(filePanel, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												jPanel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSeparator1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												10,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												mainMemoryPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												monetPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												307,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												filePanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jPanel8,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(
												jPanel9,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void doneButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_doneButtonMouseClicked
		try {
			if (doneButton.getText().equalsIgnoreCase("Done")) {
				this.dispose();
				return;
			}
			synchronized (main) {
				msgLabel.append("\nsetting storage type ... \n");
				if (main.fuzzySystem != null) {
					main.fuzzySystem.close();
				}
				if (fileRB.isSelected()) {
					String fileName = fileTextField.getText();
					msgLabel.append("storage type = file\n");
					main.fuzzySystem = new FuzzySystemFile(fileName,
							InfLevel.ALL_INF.ordinal());
					msgLabel.append("OK\n");
				} else if (mainMemoryRB.isSelected()) {
					msgLabel.append("storage type = main memory\n");
					main.fuzzySystem = new FuzzySystemMainMemory(
							InfLevel.ALL_INF.ordinal());
					msgLabel.append("OK\n");
				} else if (monetRB.isSelected()) {
					String databaseName = databaseNameField.getText();
					String userName = userNameField.getText();
					String password = new String(passwordField.getPassword());
					msgLabel.append("storage type = monetdb\n");
					if (localhostRB.isSelected()) {
						main.fuzzySystem = new FuzzySystemMonetdb(databaseName,
								userName, password, InfLevel.ALL_INF.ordinal());
					} else if (otherLocationRB.isSelected()) {
						String location = otherLocationRB.getText();
						main.fuzzySystem = new FuzzySystemMonetdb(databaseName,
								userName, password, location, InfLevel.ALL_INF
										.ordinal());
					} else {
						throw new RuntimeException();
					}
					msgLabel.append("OK\n");
				} else {
					throw new RuntimeException();
				}
			}
			msgLabel.setForeground(java.awt.Color.BLACK);
			msgLabel.append("storage option set correctly");
			doneButton.setText("Done");
		} catch (Exception e) {
			GUIView.showException(e, msgLabel);
		}
	}// GEN-LAST:event_doneButtonMouseClicked

	private void fileRBMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_fileRBMouseClicked
		doneButton.setText("Set storage option");
	}// GEN-LAST:event_fileRBMouseClicked

	private void monetRBMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_monetRBMouseClicked
		doneButton.setText("Set storage option");
	}// GEN-LAST:event_monetRBMouseClicked

	private void mainMemoryRBMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_mainMemoryRBMouseClicked
		doneButton.setText("Set storage option");
	}// GEN-LAST:event_mainMemoryRBMouseClicked

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.ButtonGroup buttonGroup2;
	private javax.swing.JTextField databaseNameField;
	private javax.swing.JButton doneButton;
	private javax.swing.JPanel filePanel;
	private javax.swing.JRadioButton fileRB;
	private javax.swing.JTextField fileTextField;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JRadioButton localhostRB;
	private javax.swing.JTextField locationField;
	private javax.swing.JPanel mainMemoryPanel;
	private javax.swing.JRadioButton mainMemoryRB;
	private javax.swing.JPanel monetPanel;
	private javax.swing.JRadioButton monetRB;
	private javax.swing.JTextArea msgLabel;
	private javax.swing.JRadioButton otherLocationRB;
	private javax.swing.JPasswordField passwordField;
	private javax.swing.JTextField userNameField;
	// End of variables declaration//GEN-END:variables
}
